// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCT9KgTbR7PRHRremDwBHq_2HuFbGmqEjI',
    appId: '1:660054968169:web:c5b58c2eefd286c5f01ff8',
    messagingSenderId: '660054968169',
    projectId: 'kitabcorner-be8ee',
    authDomain: 'kitabcorner-be8ee.firebaseapp.com',
    storageBucket: 'kitabcorner-be8ee.firebasestorage.app',
    measurementId: 'G-Y8ETZ5WG6W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-x-GXHmotgEewQFpUt-m3cYGRqUuSnNA',
    appId: '1:660054968169:android:f2bf392c4bc10763f01ff8',
    messagingSenderId: '660054968169',
    projectId: 'kitabcorner-be8ee',
    storageBucket: 'kitabcorner-be8ee.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQ55gPj9SH-_CR21L0xXeJ6L_BUM02B5c',
    appId: '1:660054968169:ios:568b63a847ee38a4f01ff8',
    messagingSenderId: '660054968169',
    projectId: 'kitabcorner-be8ee',
    storageBucket: 'kitabcorner-be8ee.firebasestorage.app',
    iosBundleId: 'com.example.myflutterapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDQ55gPj9SH-_CR21L0xXeJ6L_BUM02B5c',
    appId: '1:660054968169:ios:568b63a847ee38a4f01ff8',
    messagingSenderId: '660054968169',
    projectId: 'kitabcorner-be8ee',
    storageBucket: 'kitabcorner-be8ee.firebasestorage.app',
    iosBundleId: 'com.example.myflutterapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCT9KgTbR7PRHRremDwBHq_2HuFbGmqEjI',
    appId: '1:660054968169:web:8bac966fcedc897ff01ff8',
    messagingSenderId: '660054968169',
    projectId: 'kitabcorner-be8ee',
    authDomain: 'kitabcorner-be8ee.firebaseapp.com',
    storageBucket: 'kitabcorner-be8ee.firebasestorage.app',
    measurementId: 'G-PRV0S8T3R6',
  );

}